project_id = "izspjvegxdfgkgibpyst"

[functions.gerar-conteudo-conceitos]
verify_jwt = false

[functions.gerar-capa-dominando-area]
verify_jwt = false

[functions.gerar-conteudo-dominando]
verify_jwt = false

[functions.processar-videoaula-oab]
verify_jwt = false

[functions.reset-conceitos-topicos]
verify_jwt = false

[functions.formatar-lei-push-unica]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.gerar-artigo-blog]
verify_jwt = false

[functions.gerar-audio-feedback]
verify_jwt = false

[functions.gerar-definicao-termo]
verify_jwt = false

[functions.sincronizar-videoaulas-oab-primeira-fase]
verify_jwt = false
